name: Create release pull request
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump Type (minor or major)'
        required: true
        default: 'minor'
jobs:
  check-params:
    name: Check status
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.event.inputs.bump_type != 'minor' || github.event.inputs.bump_type != 'major'
    steps:
      - name: failure
        run: exit 1
  bump-version-ios:
    name: Bump version iOS
    needs: [check-params]
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: develop
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'
      - name: Increment version
        run: |
          bundle install
          bundle exec fastlane ios bump_version bump_type:${{ github.event.inputs.bump_type }}
  bump-version-android:
    name: Bump version Android
    needs: [check-params, bump-version-ios]
    runs-on: ubuntu-latest
    if: env.NEW_VERSION != null
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: develop
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Increment version
        run: |
          bundle install
          bundle exec fastlane android bump_version bump_type:${{ env.NEW_VERSION }}