name: Create release pull request
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump Type (minor or major)'
        required: true
        default: 'minor'
jobs:
  bump-version-ios:
    name: Bump version iOS
    runs-on: macos-latest
    if: github.event.inputs.bump_type == 'minor' || github.event.inputs.bump_type == 'major'
    outputs:
      new-version: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: develop
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'
      - name: Bump version
        id: bump_version
        run: |
          bundle install
          bundle exec fastlane ios bump_version bump_type:${{ github.event.inputs.bump_type }}
          echo ::set-output name=new_version::${{ env.IOS_NEW_VERSION }}
  bump-version-android:
    name: Bump version Android
    runs-on: ubuntu-latest
    if: github.event.inputs.bump_type == 'minor' || github.event.inputs.bump_type == 'major'
    outputs:
      new-version: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: develop
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Bump version
        id: bump_version
        run: |
          bundle install
          bundle exec fastlane android bump_version bump_type:${{ github.event.inputs.bump_type }}
          echo ::set-output name=new_version::${{ env.ANDROID_NEW_VERSION }}
  create-release-pr:
    name: Create release pull request
    needs: [bump-version-ios, bump-version-android]
    runs-on: ubuntu-latest
    if: needs.bump-version-ios.outputs.new-version == needs.bump-version-android.outputs.new-version
    steps:
      - name: check
        run: git status
